#!/bin/bash
# JARVIS v3.0 — Phase 0 Implementation Checklist
# Run this as reference during development

# Color codes for terminal
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  JARVIS v3.0 — Phase 0 Quick Wins Implementation${NC}"
echo -e "${BLUE}  30 April 2026 | Duration: 2-3 hours${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${YELLOW}📋 PHASE 0 CHECKLIST${NC}"
echo ""

# ─── PREREQUISITES ───────────────────────────────────────────────────────────

echo -e "${YELLOW}[STEP 0] Prerequisites${NC}"
echo "  [ ] Git branch created: git checkout -b feature/phase-0-quick-wins"
echo "  [ ] Python venv activated: source venv/bin/activate"
echo "  [ ] Ollama running: ollama serve (in another terminal)"
echo "  [ ] Working directory: /home/gaetal/Desktop/jarvis-core-fixed"
echo ""

# ─── FEATURE 1: TOKEN COUNTER ────────────────────────────────────────────────

echo -e "${YELLOW}[FEATURE 1] Token Counter${NC}"
echo "  Deliverable: core/token_counter.py"
echo ""
echo "  [ ] Create file: core/token_counter.py"
echo "  [ ] Implement TokenCounter class with:"
echo "      - estimate_tokens(text, model) → int"
echo "      - format_usage(prompt_tokens, completion_tokens) → str"
echo "      - TOKEN_RATIOS dict for different models"
echo "  [ ] Add unit tests at bottom"
echo "  [ ] Test: python core/token_counter.py"
echo "  [ ] Check output format: '📊 Tokens: X prompt + Y completion = Z total'"
echo ""
echo "  Integration points:"
echo "  [ ] Import in core/llm.py"
echo "  [ ] Track tokens from stream_llm()"
echo "  [ ] Display in ui/cli.py after JARVIS response"
echo ""

# ─── FEATURE 2: MODEL SWITCH ─────────────────────────────────────────────────

echo -e "${YELLOW}[FEATURE 2] Model Switch (/model command)${NC}"
echo "  Deliverable: Modify core/commands.py"
echo ""
echo "  [ ] Add function: get_available_models()"
echo "      - Queries Ollama /api/tags"
echo "      - Returns list of model names"
echo "      - Handles connection errors gracefully"
echo ""
echo "  [ ] Add function: handle_model_command(args)"
echo "      - Subcommands: list | set | current"
echo "      - /model list → shows available models"
echo "      - /model set [name] → switches model"
echo "      - /model current → shows current model"
echo ""
echo "  [ ] Add 'model' to COMMANDS registry"
echo "  [ ] Update help text with emoji"
echo ""
echo "  Testing:"
echo "  [ ] /model list → lists 2+ models"
echo "  [ ] /model set [valid_model] → ✅ success message"
echo "  [ ] /model set invalid_model → ❌ error message"
echo "  [ ] /model current → shows selected model"
echo ""

# ─── FEATURE 3: MARKDOWN RENDERING ───────────────────────────────────────────

echo -e "${YELLOW}[FEATURE 3] Markdown Rendering${NC}"
echo "  Deliverable: Modify ui/cli.py"
echo ""
echo "  [ ] Import: from rich.markdown import Markdown"
echo "  [ ] Add function: _has_markdown(text) → bool"
echo "      - Detects **, __, `, #, -, >, *, etc."
echo "      - Returns True if any pattern found"
echo ""
echo "  [ ] Modify: render_jarvis_panel(text)"
echo "      - Use Markdown(text) if _has_markdown(text)"
echo "      - Fall back to Text(text) if plain"
echo "      - Keep styling consistent"
echo ""
echo "  Testing:"
echo "  [ ] Ask something formatted: 'Dammi 3 motivi per...' "
echo "  [ ] Verify bullet points render as - items"
echo "  [ ] Verify **bold** renders bold"
echo "  [ ] Verify `code` renders monospace"
echo "  [ ] Verify no markdown → plain text fallback"
echo ""

# ─── FEATURE 4: CHAT EXPORT ──────────────────────────────────────────────────

echo -e "${YELLOW}[FEATURE 4] Chat Export (/export)${NC}"
echo "  Deliverable: Create core/export.py + modify core/commands.py"
echo ""
echo "  [ ] Create file: core/export.py"
echo "  [ ] Implement ChatExporter class with:"
echo "      - __init__(export_dir='exports')"
echo "      - export_memory(memory_data, filename=None) → str"
echo "      - Generates markdown with:"
echo "        * Title: # JARVIS Chat Export"
echo "        * Timestamp: **Exported:** 30/04/2026 14:30:00"
echo "        * Conversation formatted as ## User / ## JARVIS sections"
echo "        * Footer with total messages count"
echo "      - Returns success/error message"
echo ""
echo "  [ ] Test export_memory() with sample data"
echo "      - python core/export.py"
echo "      - Verify file created in exports/"
echo ""
echo "  [ ] Modify core/commands.py:"
echo "      - Import ChatExporter"
echo "      - Create exporter = ChatExporter() singleton"
echo "      - Add handle_export_command(args)"
echo "      - Add 'export' to COMMANDS registry"
echo ""
echo "  [ ] Create exports/ directory: mkdir exports"
echo ""
echo "  Testing:"
echo "  [ ] In JARVIS CLI: /export"
echo "  [ ] Check exports/ contains jarvis_chat_YYYYMMDD_HHMMSS.md"
echo "  [ ] Verify .md file has proper formatting"
echo "  [ ] Check file is readable markdown"
echo ""

# ─── INTEGRATION TESTING ─────────────────────────────────────────────────────

echo -e "${YELLOW}[STEP 1] Integration Testing${NC}"
echo ""
echo "  [ ] Start JARVIS: python main.py"
echo "  [ ] Run through all features:"
echo ""
echo "      Test Token Counter:"
echo "        > 2 + 2"
echo "        [Check for 📊 Tokens: X + Y = Z]"
echo ""
echo "      Test Model Switch:"
echo "        > /model list"
echo "        > /model set neural-chat"
echo "        > /model current"
echo ""
echo "      Test Markdown:"
echo "        > Dammi 5 oggetti con colori"
echo "        [Verify list rendering with bullets]"
echo ""
echo "      Test Export:"
echo "        > /export test_phase0"
echo "        [Verify exports/test_phase0.md created]"
echo ""
echo "  [ ] Check logs: tail logs/*.log"
echo "  [ ] Verify no ERROR/CRITICAL entries"
echo ""

# ─── FILE CHECKLIST ──────────────────────────────────────────────────────────

echo -e "${YELLOW}[STEP 2] Files Created/Modified${NC}"
echo ""
echo "  NEW FILES:"
echo "    [ ] core/token_counter.py (150 lines)"
echo "    [ ] core/export.py (100 lines)"
echo "    [ ] exports/ (directory)"
echo ""
echo "  MODIFIED FILES:"
echo "    [ ] core/commands.py (add model + export handlers)"
echo "    [ ] core/llm.py (optional: token tracking)"
echo "    [ ] ui/cli.py (add markdown rendering)"
echo ""

# ─── DOCUMENTATION ───────────────────────────────────────────────────────────

echo -e "${YELLOW}[STEP 3] Documentation${NC}"
echo ""
echo "  [ ] Update QUICKSTART.md with new commands:"
echo "      - /model list, /model set, /model current"
echo "      - /export [filename]"
echo ""
echo "  [ ] Update README.md if needed"
echo "  [ ] Add comments to new functions"
echo "  [ ] Verify no type errors (optional: add type hints)"
echo ""

# ─── GIT COMMIT ───────────────────────────────────────────────────────────────

echo -e "${YELLOW}[STEP 4] Git Commits${NC}"
echo ""
echo "  Recommended commit sequence:"
echo "  [ ] git add core/token_counter.py"
echo "      git commit -m 'feat: add token counter for LLM usage tracking'"
echo ""
echo "  [ ] git add core/export.py"
echo "      git commit -m 'feat: add chat export to markdown'"
echo ""
echo "  [ ] git add core/commands.py ui/cli.py"
echo "      git commit -m 'feat: add /model switch and /export commands'"
echo ""
echo "  [ ] git add ui/cli.py"
echo "      git commit -m 'feat: add markdown rendering support'"
echo ""
echo "  [ ] git add QUICKSTART.md IMPROVEMENTS.md"
echo "      git commit -m 'docs: update guides for Phase 0'"
echo ""

# ─── COMPLETION ───────────────────────────────────────────────────────────────

echo -e "${YELLOW}[FINAL] Completion Verification${NC}"
echo ""
echo "  Phase 0 is COMPLETE when:"
echo ""
echo "  ✅ Checklist Items:"
echo "    [ ] All 4 features implemented and tested"
echo "    [ ] No import errors"
echo "    [ ] No crashes in CLI"
echo "    [ ] Logs show no ERROR entries"
echo "    [ ] Git commits created"
echo ""
echo "  ✅ Feature Verification:"
echo "    [ ] Token counter shows after responses"
echo "    [ ] /model switch changes active model"
echo "    [ ] Markdown renders in responses"
echo "    [ ] /export creates .md files"
echo ""
echo "  ✅ Ready for Phase 1:"
echo "    [ ] Branch pushed: git push -u origin feature/phase-0-quick-wins"
echo "    [ ] PR created (optional)"
echo "    [ ] Code reviewed"
echo ""

# ─── TIMING ───────────────────────────────────────────────────────────────────

echo -e "${YELLOW}⏱️  Estimated Timing${NC}"
echo ""
echo "  Token Counter:        25-30 min"
echo "  Model Switch:         20-25 min"
echo "  Markdown Rendering:   15-20 min"
echo "  Chat Export:          30-40 min"
echo "  Integration Testing:  20-25 min"
echo "  Documentation:        10-15 min"
echo "  ─────────────────────────────────"
echo "  TOTAL:                2-3 hours"
echo ""

# ─── HELPFUL COMMANDS ─────────────────────────────────────────────────────────

echo -e "${YELLOW}🔧 Helpful Commands${NC}"
echo ""
echo "  # Start development"
echo "  cd /home/gaetal/Desktop/jarvis-core-fixed"
echo "  source venv/bin/activate"
echo "  ollama serve                    # Terminal 1"
echo "  python main.py                  # Terminal 2"
echo ""
echo "  # Testing individual features"
echo "  python core/token_counter.py    # Test token counter"
echo "  python core/export.py           # Test export"
echo ""
echo "  # Check logs"
echo "  tail -f logs/jarvis.log"
echo ""
echo "  # Git workflow"
echo "  git status"
echo "  git diff"
echo "  git add ."
echo "  git commit -m 'feat: Phase 0 complete'"
echo ""

# ─── TROUBLESHOOTING ──────────────────────────────────────────────────────────

echo -e "${YELLOW}🔍 Troubleshooting${NC}"
echo ""
echo "  Problem: 'ModuleNotFoundError: rich'"
echo "  Solution: pip install rich (should already be installed)"
echo ""
echo "  Problem: '/model list' returns error"
echo "  Solution: Ensure Ollama running (ollama serve)"
echo ""
echo "  Problem: Export file not created"
echo "  Solution: Check exports/ directory exists + permissions"
echo ""
echo "  Problem: Markdown not rendering"
echo "  Solution: Check _has_markdown() detects patterns (**, #, etc.)"
echo ""
echo "  Problem: Token counter imports fail"
echo "  Solution: Verify core/token_counter.py created correctly"
echo ""

# ─── NEXT PHASE ───────────────────────────────────────────────────────────────

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  After Phase 0 ✅${NC}"
echo -e "${BLUE}  Next: Start Phase 1 (Robustezza Core)${NC}"
echo -e "${BLUE}  Read: PHASE_1_GUIDE.md${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

